"""Adiciona coluna data_ultima_resposta

Revision ID: 2d90499ba38b
Revises: 1adf42d1be3d
Create Date: 2025-06-09 20:44:41.398230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d90499ba38b'
down_revision = '1adf42d1be3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocorrencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_ultima_resposta', sa.DateTime(), nullable=True))
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocorrencia', schema=None) as batch_op:
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('data_ultima_resposta')

    # ### end Alembic commands ###
